# Generated by Django 4.1 on 2023-12-18 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Task_title', models.CharField(max_length=50)),
                ('Task_description', models.TextField()),
                ('Task_status', models.CharField(max_length=30)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
